import type { SheetSchema } from './types'

/** Stockfeel CDP order / purchase records — see csv_example/example_orders.csv */
export const ordersSchema: SheetSchema = {
  id: 'orders',
  title: '訂單紀錄',
  description: 'Purchase and order line items linked to members',
  version: '1.0.0',
  exampleFile: 'example_orders.csv',
  fields: [
    {
      key: '訂單編號',
      label: '訂單編號',
      required: true,
      type: 'string',
      aliases: ['order_id', 'order_number', '訂單編號'],
    },
    {
      key: '訂單時間',
      label: '訂單時間',
      required: true,
      type: 'date',
      dateFormat: 'slash',
      aliases: ['order_date', 'purchased_at', '訂單產生時間', 'order_time'],
    },
    {
      key: '訂單狀態',
      label: '訂單狀態',
      required: false,
      type: 'string',
      aliases: ['order_status', 'status'],
    },
    {
      key: '總計',
      label: '總計',
      required: true,
      type: 'number',
      aliases: ['total', 'amount', 'order_total'],
    },
    {
      key: '歸戶碼',
      label: '歸戶碼',
      required: true,
      type: 'string',
      aliases: ['member_id', 'user_id', 'customer_id', 'cust_id'],
    },
    {
      key: '手機',
      label: '手機',
      required: false,
      type: 'string',
      aliases: ['phone', 'mobile'],
    },
    {
      key: 'Email',
      label: 'Email',
      required: false,
      type: 'email',
      aliases: ['email', 'member_email'],
    },
    {
      key: '會員名稱',
      label: '會員名稱',
      required: false,
      type: 'string',
      aliases: ['user_name', 'member_name'],
    },
    {
      key: '商品編號',
      label: '商品編號',
      required: true,
      type: 'string',
      aliases: ['product_id', 'sku', 'product_sku', '商品編號'],
    },
    {
      key: '商品名稱',
      label: '商品名稱',
      required: false,
      type: 'string',
      aliases: ['product_name', '商品名稱'],
    },
    {
      key: '商品規格',
      label: '商品規格',
      required: false,
      type: 'string',
      aliases: ['variant', 'spec', '商品規格'],
    },
    {
      key: '數量',
      label: '數量',
      required: true,
      type: 'number',
      aliases: ['quantity', 'qty'],
    },
    {
      key: '商品原價',
      label: '商品原價',
      required: false,
      type: 'number',
      aliases: ['list_price', 'original_price'],
    },
    {
      key: '商品售價',
      label: '商品售價',
      required: false,
      type: 'number',
      aliases: ['sale_price', 'unit_price'],
    },
    {
      key: '小計',
      label: '小計',
      required: false,
      type: 'number',
      aliases: ['subtotal', 'line_total'],
    },
    {
      key: '出貨地址',
      label: '出貨地址',
      required: false,
      type: 'string',
      aliases: ['shipping_address', 'address'],
    },
    {
      key: '商品類別',
      label: '商品類別',
      required: false,
      type: 'string',
      aliases: ['category', 'product_category'],
    },
  ],
}
